[tools]
bazel = 'latest'
crystal = 'latest'
ctop = 'latest'
docker-slim = 'latest'
go = 'latest'
kubectl = 'latest'
minikube = 'latest'
node = ['latest', '20']
pnpm = 'latest'
python = ['latest']
ruby = 'latest'
shellcheck = 'latest'
shfmt = 'latest'
yarn = 'latest'
yt-dlp = 'latest'
usage = 'latest'

[settings]
activate_aggressive = true
always_keep_download = false        # deleted after install by default
always_keep_install = false         # deleted on failure by default
asdf_compat = false
env_file = '.env' # load env vars from a dotenv file, see `MISE_ENV_FILE`
experimental = true # enable experimental features
go_default_packages_file = "~/.default-go-packages"
go_set_gopath = false
go_set_goroot = false
go_skip_checksum = true
jobs = 8            # number of plugins or runtimes to install in parallel. The default is `4`.
legacy_version_file = true
not_found_auto_install = true # see MISE_NOT_FOUND_AUTO_INSTALL
paranoid = false       # see MISE_PARANOID
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr
task_output = 'prefix' # see Task Runner for more information
verbose = false     # set to true to see full installation output, see `MISE_VERBOSE`
yes = true
trusted_config_paths = [
  '~/code',
  '~/src',
]
disable_hints = ["python_multi"]

[settings.ruby]
default_packages_file = "~/.default-gems"
# ruby_install = true
