default-scheme = "base16-tomorrow-night"
shell = "bash -c '{}'"

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "source %f"

[[items]]
name = "tinted-vim"
path = "https://github.com/tinted-theming/tinted-vim"
themes-dir = "colors"

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
themes-dir = "sh"

[[items]]
name = "tinted-iterm2"
path = "https://github.com/tinted-theming/tinted-iterm2"
themes-dir = "scripts"
hook = "command -v osascript >&/dev/null && bash %f"
