"$schema" = 'https://starship.rs/config-schema.json'


add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
${custom.derp}\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$directory\
$line_break\
$time\
$localip\
$cmd_duration\
$status\
$character\
"""

right_format = """
$mise\
$nodejs\
$ruby\
$rust\
$golang\
$elixir\
$java\
$python\
$pulumi\
$username\
$hostname\
"""

[custom.derp]
disabled = false
when = true
format = '>'

[mise]
disabled = false
symbol = ''
healthy_symbol = ''
unhealthy_symbol = ' mise-unhealthy'
format = '[$health]($style)'

[nodejs]
style = ''
version_format = 'node-${raw}'
format = ' [$version]($style)'

[rust]
disabled = false
version_format = 'rust-${raw}'
format = ' [$version]($style)'

[golang]
disabled = false
version_format = 'go-${raw}'
format = ' [$version]($style)'

[ruby]
disabled = false
version_format = 'ruby-${raw}'
format = ' [$version]($style)'

[python]
disabled = false
version_format = 'python-${raw}'
format = ' [$version]($style)'

[directory]
disabled = false
format = "[ $path]($style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
disabled = false
symbol = ""
format = ' [[$symbol $branch]()]($style)'

[git_commit]
disabled = false
tag_symbol = " tag "

[git_status]
disabled = false
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
format = ' [[($all_status$ahead_behind)]()]($style)'

[git_state]
disabled = false
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = 'blue'
format = '[$time]($style)'

[username]
disabled = false
style_root = 'bold red'
style_user = 'white'
format = ' [$user]($style)'

[hostname]
disabled = false
ssh_only = false
style = 'white'
format = ' [$ssh_symbol@$hostname]($style)'
trim_at = ''

[cmd_duration]
disabled = false
min_time = 1
show_notifications = false
style = "yellow"
format = ' [$duration]($style)'

[status]
disabled = false
style = 'white'
success_style = 'white'
failure_style = 'bold red'
symbol = ''
success_symbol = '0'
map_symbol = false
recognize_signal_code = false
format = ' [$status]($style)'

[character]
format = ' [$symbol]($style) '
